Concurent Web
irusland/todo-liost pull request #4
Opened 2021-12-11 13:01 UTC by irusland

2021-12-14 18:28 UTC, mrdekk commented on TodoLiost/Main/MainViewController.swift
> +    private var storage: PresistantStorage
PersistentStorage (а не Presistant)

2021-12-14 18:29 UTC, mrdekk commented on TodoLiost/Main/Net/Auth.swift
> +class Auth: UIViewController, IAuthentificator, URLSessionDataDelegate {
нейминг у класса не очень, он типо UIViewController, но по названию это никак не понятно

2021-12-14 18:30 UTC, mrdekk commented on TodoLiost/Main/Net/Auth.swift
> +    var authCredentials: OAuthCredentials?
Может быть let и передавать через инициализатор - так будет правильнее

2021-12-14 18:31 UTC, mrdekk commented on TodoLiost/Main/Net/Auth.swift
> +    var authCredentials: OAuthCredentials?
Увидел что мы их получаем внутри, а не сетим
Тогда правильнее их сделать private(set) чтобы извне установить было нельзя

2021-12-14 18:35 UTC, mrdekk commented on TodoLiost/Main/Net/Endpoint.swift
> +struct Endpoint {
В целом интересное решение

2021-12-14 18:36 UTC, mrdekk commented on TodoLiost/Main/Net/Request.swift
> +//  Request.swift
Обычно файли с экстеншнами называют RequestExtensions в Swift

2021-12-14 18:36 UTC, mrdekk commented on TodoLiost/Main/Net/Request.swift
> +//  Request.swift
Или еще по старому можно Request+HeaderModifiers

2021-12-14 18:37 UTC, mrdekk commented on TodoLiost/Main/Net/ResponseModels.swift
> +            createdAt: Date().unixTimestamp,
синхронизатор так работать не будет, вам надо вашу локальную модель расширить, чтобы трекать дату создания и изменения

2021-12-14 18:37 UTC, mrdekk commented on TodoLiost/Main/Net/ResponseModels.swift
> +            lastUpdatedBy: UUID.init()
А тут надо один раз при первом запуске сгенерировать UUID и пользоваться им всегда
это индентификатор конкретного клиента

2021-12-14 18:38 UTC, mrdekk commented on TodoLiost/Main/SquaresViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
Зачем так?

2021-12-14 18:38 UTC, mrdekk commented on TodoLiost/Main/SquaresViewController.swift
> +            self.sync()
Лучше это делать после успешной авторизации

2021-12-14 18:39 UTC, mrdekk commented on TodoLiost/Main/SquaresViewController.swift
> +        DispatchQueue.main.async { [weak self] in
Зачем DispatchQueue.main.async внутри ViewController'а?

2021-12-14 18:40 UTC, mrdekk commented on TodoLiost/Main/Storage/Storage.swift
> +        self.result = self.cloudStorage.todoItems
вот вы там спрятали асинхронные операции за синхронным интерфейсом, хотя можно было бы сюда протащить callback и finish вызывать внутри него

2021-12-14 18:41 UTC, mrdekk commented on TodoLiost/Main/Storage/Storage.swift
> +        self.result = self.cloudStorage.todoItems
и self можно не писать когда это явно не нужно

2021-12-14 18:41 UTC, mrdekk commented on TodoLiost/Main/Storage/Storage.swift
> +class NotifyOperation: Operation {
зачем это?

2021-12-14 18:42 UTC, mrdekk commented on TodoLiost/Main/Storage/Storage.swift
> +class AsyncExecutionOperation<T>: AsyncOperation {
AsyncBlockOperation (в системе есть BlockOperation которая имеет похожий интерфейс, но синхронная)

2021-12-14 18:42 UTC, mrdekk commented on TodoLiost/Main/Storage/Storage.swift
> +class ComparisonOperation<T: Equatable>: AsyncOperation {
Зачем? да еще и асинхронно?

2021-12-14 18:43 UTC, mrdekk requested changes
посмотрел

2021-12-14 20:03 UTC, irusland commented on TodoLiost/Main/Net/Endpoint.swift
> +struct Endpoint {
Да, я не хотел все время помнить что нужно прокидывать тому или иному эндпоинту, поэтому инкапсулировал все в этой структуре, и при использовании она сама требования что ей нужно выдвигает :)

2021-12-14 20:07 UTC, irusland commented on TodoLiost/Main/SquaresViewController.swift
> +        DispatchQueue.main.async { [weak self] in
Я из Operation в DispatchQueue вызываю этот коллбэк и Xcode ругается на то, что изменение UI компонента было произведено не из UI потока

2021-12-15 19:22 UTC, irusland commented on TodoLiost/Main/Storage/Storage.swift
> +class NotifyOperation: Operation {
Я может быть не правильно вас понял, но вы сказали Операции должны быть маленькие и делающие какую-то одну вещь, я вот так разделил

2021-12-18 07:01 UTC, irusland commented
В новую прку подолью, как эту смержим https://github.com/irusland/todo-liost/pull/5

2021-12-19 17:38 UTC, mrdekk commented on TodoLiost/Main/Net/BackendConnector.swift
> +    func getList(handler: @escaping (ListModel?, BackendErrors?) -> Void, using session: URLSession = .shared) {
handler лучше так
```
handler: @escaping (Result<ListModel, BackendErrors>) -> Void
```
тогда не будет ситуаций где надо хитро проверять какой из параметров есть

2021-12-19 17:38 UTC, mrdekk commented on TodoLiost/Main/Net/BackendConnector.swift
> +    func getList(handler: @escaping (ListModel?, BackendErrors?) -> Void, using session: URLSession = .shared) {
ну и с остальными также

2021-12-19 17:39 UTC, mrdekk commented on TodoLiost/Main/Net/BackendErrors.swift
> +public enum BackendErrors: Error {
обычно BackendError

2021-12-19 17:42 UTC, mrdekk commented on TodoLiost/Main/Storage/Storage.swift
> +            alert.addAction(UIAlertAction(title: title, style: .default, handler: action))
action'ы бы лучше обернуть тут и звать self.finish
иначе эта операция кажется никогда не завершается

2021-12-19 17:44 UTC, mrdekk commented
зачту

2021-12-19 17:44 UTC, mrdekk approved these changes

2021-12-20 14:12 UTC, merged